import { ActionIcon, Skeleton, Text, Title, Tooltip } from '@mantine/core';
import { IconRefresh } from '@tabler/icons-react';
import { useSelector } from 'react-redux';
import { Filters, RenderPosts, ScrollToTopButton } from '../../components';
import { useFetchPosts, useSearchPosts } from '../../hooks';
import { selectPosts, selectPostsFilters, selectSearchedPosts, selectSearchText } from '../../redux/selectors';
import { resetPostsFilters, resetPostsSearch, setPosts, setPostsFilters, setPostsSearchText } from '../../redux/slices';
import { SearchPostsInput } from '../components';

export const HomePage = () => {
  const posts = useSelector(selectPosts);

  const { fetchPosts, loading, firstLoad } = useFetchPosts();
  const { searchText, searchedPosts, handleSearchChange, resetSearchedPosts } = useSearchPosts(
    selectSearchText,
    selectSearchedPosts,
    setPostsSearchText,
    resetPostsSearch
  );

  return (
    <section className='mx-auto max-w-7xl'>
      <div className='flex flex-col items-start justify-between gap-5 md:flex-row'>
        <div>
          <Title order={1}>The Community Showcase</Title>

          <Text className='mt-2 max-w-[500px] opacity-60'>
            Browse through a collection of imaginative and visually stunning images generated by AI
          </Text>
        </div>
      </div>

      {firstLoad && loading ? (
        <Skeleton radius='md' height={42} className='mt-14' />
      ) : (
        !!posts.length && (
          <div className='mt-8 flex items-end gap-x-2'>
            <SearchPostsInput
              placeholder='Enter prompt or username'
              loading={loading}
              searchText={searchText}
              handleSearchChange={handleSearchChange}
              resetSearch={resetSearchedPosts}
            />

            <Tooltip label='Refresh posts' withArrow>
              <ActionIcon
                size={42}
                color='violet'
                radius='md'
                onClick={() => {
                  resetSearchedPosts();
                  fetchPosts();
                }}
                loading={loading}
                aria-label='Refresh'
              >
                <IconRefresh size={20} />
              </ActionIcon>
            </Tooltip>

            <Filters
              postsSelector={selectPosts}
              setPosts={setPosts}
              filtersStateSelector={selectPostsFilters}
              setFiltersState={setPostsFilters}
              resetFilters={resetPostsFilters}
            />
          </div>
        )
      )}

      <div className='mt-3'>
        {searchText && (
          <Title className='mb-3 font-medium' order={2} size={'h3'}>
            <span className='opacity-60'>Showing results for</span> <span className='opacity-100'>{searchText}</span>
          </Title>
        )}

        <RenderPosts title='No posts found' posts={searchText ? searchedPosts : posts} loading={loading} />
      </div>

      <ScrollToTopButton />
    </section>
  );
};
