import { useState } from 'react';
import { Link } from 'react-router-dom';
import { LuImagePlus } from 'react-icons/lu';
import { TbRefresh } from 'react-icons/tb';
import { useSelector } from 'react-redux';

import { Input } from '../../components';
import { Post } from '../../types/post.interface';
import useFetchPosts from '../../hooks/useFetchPosts';
import { RootState } from '../../redux/store';
import RenderCards from './components/RenderCards';

const Home = () => {
  const [searchText, setSearchText] = useState<string>('');
  const [searchedPosts, setSearchedPosts] = useState<Post[]>([]);

  const { isLoading, fetchPosts } = useFetchPosts();

  const posts = useSelector((state: RootState) => state.posts.posts);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const value = e.target.value;

    setSearchText(value);

    const searchResults = posts.filter(
      (post) =>
        post.name.toLowerCase().includes(value.trim().toLowerCase()) ||
        post.prompt.toLowerCase().includes(value.trim().toLowerCase())
    );

    setSearchedPosts(searchResults);
  };

  return (
    <section className='max-w-7xl mx-auto'>
      <div className='flex md:flex-row gap-5 flex-col justify-between items-start'>
        <div>
          <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>

          <p className='mt-2 text-[#666E75] text-[16px] max-w-[500px]'>
            Browse through a collection of imaginative and visually stunning images generated by AI
          </p>
        </div>

        <Link
          className='font-inter font-medium bg-[#6469FF] text-white px-6 py-3 rounded-md flex items-center gap-x-2'
          to='/create-post'
        >
          Create image <LuImagePlus className='inline-block text-lg' />
        </Link>
      </div>

      <div className='mt-8 md:mt-16 flex items-end gap-x-2'>
        <Input
          className='flex-grow'
          labelName='Search posts'
          type='text'
          name='name'
          placeholder='Enter name or prompt'
          value={searchText}
          handleChange={handleSearchChange}
        />

        <button
          className='text-white bg-[#6469FF] font-medium rounded-md text-sm w-[46px] h-[46px] text-center justify-center items-center'
          type='button'
          aria-label='Refresh'
          onClick={fetchPosts}
          disabled={isLoading}
        >
          <TbRefresh className='inline-block text-lg' />
        </button>
      </div>

      <div className='mt-10'>
        {searchText && (
          <h2 className='font-medium text-[#666E75] text-xl mb-3'>
            Showing results for <span className='text-[#222328]'>{searchText}</span>
          </h2>
        )}

        <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
          {searchText ? (
            <RenderCards posts={searchedPosts} title='No search results found' isLoading={isLoading} />
          ) : (
            <RenderCards posts={posts} title='No posts found' isLoading={isLoading} />
          )}
        </div>
      </div>
    </section>
  );
};

export default Home;
